language: elixir

otp_release:
  - 18.0

elixir:
  - 1.2.0

sudo: false

script: mix test --trace

services:
  - postgresql

addons:
  postgresql: "9.4"

before_install:
  - cp config/dev.secret.exs.example config/dev.secret.exs

before_script:
  - cp config/test.secret.exs.example config/test.secret.exs
  - psql -c 'create database ex_money_test;' -U postgres
